services:
  onthespot:
    build: .
    container_name: onthespot
    ports:
      - "8083:5000" 
    environment:
      - HOME=/config
      - OTS_CONFIG_PATH=/config
    volumes:
      - ./downloads:/downloads
      - ./config:/config
    restart: unless-stopped